name: Continuous Integration
on: [push]
jobs:
    phpunit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            -
                name: PHPEnv
                run: 'ls /usr/bin | grep php'
