name: CI

on: [push]

jobs:
  blackbox:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: proofs
      cancel-in-progress: false
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.3']
    name: 'BlackBox'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Composer
        uses: "ramsey/composer-install@v3"
      - name: BlackBox
        run: php blackbox.php ci
        env:
          S3_URL: ${{ secrets.S3_URL_PROOFS }}
          S3_REGION: ${{ secrets.S3_REGION_PROOFS }}
          S3_PROPERTIES_URL: ${{ secrets.S3_PROPERTIES_URL_PROOFS }}
          S3_PROPERTIES_REGION: ${{ secrets.S3_PROPERTIES_REGION_PROOFS }}
  blackbox_coverage:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: coverage
      cancel-in-progress: false
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.3']
    name: 'BlackBox Coverage'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
      - name: Composer
        uses: "ramsey/composer-install@v3"
      - name: BlackBox
        run: php blackbox.php ci
        env:
          ENABLE_COVERAGE: 'true'
          S3_URL: ${{ secrets.S3_URL_COVERAGE }}
          S3_REGION: ${{ secrets.S3_REGION_COVERAGE }}
          S3_PROPERTIES_URL: ${{ secrets.S3_PROPERTIES_URL_COVERAGE }}
          S3_PROPERTIES_REGION: ${{ secrets.S3_PROPERTIES_REGION_COVERAGE }}
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  psalm:
    uses: innmind/github-workflows/.github/workflows/psalm-matrix.yml@main
  cs:
    uses: innmind/github-workflows/.github/workflows/cs.yml@main
    with:
      php-version: '8.2'
