name: Periodic CI

on:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  blackbox:
    runs-on: ${{ matrix.os }}
    concurrency:
      group: proofs
      cancel-in-progress: false
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['8.2', '8.3']
        dependency-versions: ['lowest', 'highest']
    name: 'BlackBox'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Composer
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: BlackBox
        run: php blackbox.php ci
        env:
          S3_URL: ${{ secrets.S3_URL_PROOFS }}
          S3_REGION: ${{ secrets.S3_REGION_PROOFS }}
